### ISSUE TITLE
I think there is a problem

### ISSUE THREAD

**Issue by shiroling** [Eric-Philippe/Glitch-Against-Humanity#1]
Hi, your project looks great but i think there is some kind of issue with your README.md file that doesn't appears on github and on your project.

PS des bisous

**Comment by Eric-Philippe** [comment]
'cause maybe the readme is empty and that the project is just not finished at all 👀
There are 21 files waiting to be pushed right now

**Comment by shiroling** [comment]
Fine I see, have a great work mate.
